Feat/ship corpse
TechnicJelle/CMGT-Project-Innovation pull request #38
Opened 2023-05-18 14:33 UTC by mRmetr0

Please check if you can kill a ship and collect the wreck (with points)

2023-05-19 18:35 UTC, TechnicJelle requested changes
Looking good already, but there are a couple things that still caught my eye:

2023-05-19 18:35 UTC, TechnicJelle commented on BattleShips_Host/Assets/Scripts/Shipwreck.cs
> +    public int Treasure => treasure;
You can swap this whole bit out for `public int Treasure { get; private set; }`

2023-05-20 14:35 UTC, mRmetr0 commented on BattleShips_Host/Assets/Scripts/Boat.cs
> +			int shipPoitns = other.GetComponent<Shipwreck>().Treasure;
Should be fixed now

2023-05-20 14:37 UTC, TechnicJelle approved these changes
lgtm now!

2023-05-20 14:37 UTC, merged